// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var Test = 0;

var Todo = 0;

var Example = 0;

exports.Test    = Test;
exports.Todo    = Todo;
exports.Example = Example;
/* No side effect */
