// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var React                        = require("react");
var ReasonReact                  = require("reason-react/src/ReasonReact.js");
var Example$ParcelReasonReactApp = require("./example.bs.js");

function echo(input) {
  return "Hello " + input;
}

var component = ReasonReact.statelessComponent("Greeting");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", undefined, "Hello " + name, ReasonReact.element(/* None */0, /* None */0, Example$ParcelReasonReactApp.make(/* array */[])));
    });
  return newrecord;
}

var greeting = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.name, /* array */[]);
      }));

exports.echo      = echo;
exports.component = component;
exports.make      = make;
exports.greeting  = greeting;
/* component Not a pure module */
